os:
  - linux
  - osx
language: perl6
perl6:
  - latest
install:
  - rakudobrew build zef
  - zef install --deps-only --/test .
script:
  - RAKUDOLIB=inst#$PWD/lib zef build .
  - RAKUDOLIB=$PWD/lib prove -e perl6 -vr t/
sudo: false
